[CI_dir]
dymola_ci_test_dir = 'dymola-ci-tests'
dymola_python_test_dir = 'Modelica-CI'

[whitelist]
wh_ci_dir = "dymola-ci-tests/ci_whitelist"
wh_model_file = 'dymola-ci-tests/ci_whitelist/ci_check_whitelist.txt'
wh_simulate_file = 'dymola-ci-tests/ci_whitelist/ci_simulate_whitelist.txt'
wh_html_file = 'dymola-ci-tests/ci_whitelist/ci_html_whitelist.txt'
wh_ref_file = 'dymola-ci-tests/ci_whitelist/ci_reference_check_whitelist.txt'

[config_ci]
config_ci_dir = 'dymola-ci-tests/Configfiles'
config_ci_exit_file = 'dymola-ci-tests/Configfiles/exit.sh'
config_ci_new_ref_file = 'dymola-ci-tests/Configfiles/ci_new_ref_file.txt'
config_ci_new_create_ref_file = 'dymola-ci-tests/Configfiles/ci_new_created_reference.txt'
config_ci_changed_file = 'dymola-ci-tests/Configfiles/ci_changed_model_list.txt'
config_ci_ref_file = 'dymola-ci-tests/Configfiles/ci_reference_list.txt'
config_ci_eof_file = 'dymola-ci-tests/Configfiles/EOF.sh'

[plot]
chart_dir = 'dymola-ci-tests/charts'
temp_chart_dir = 'Modelica-CI/templates/google_templates'
temp_chart_file = 'Modelica-CI/templates/google_templates/google_chart.txt'
temp_index_file = 'Modelica-CI/templates/google_templates/index.txt'
temp_layout_file = 'Modelica-CI/templates/google_templates/layout_index.txt'

[interact_ci_list]
ci_interact_dir = 'dymola-ci-tests/interact_CI'
ci_interact_show_ref_file = 'dymola-ci-tests/interact_CI/show_ref.txt'
ci_interact_update_ref_file = 'dymola-ci-tests/interact_CI/update_ref.txt'

[artifcats]
artifacts_dir = 'dymola-ci-tests/templates/artifacts'
library_ref_results_dir = 'Resources/ReferenceResults/Dymola'
library_resource_dir = 'Resources/Scripts/Dymola'

[Dymola_Python_Tests]
dymola_python_test_url = '--single-branch --branch 03_openModelica https://github.com/RWTH-EBC/Modelica-CI.git'

[result]
result_dir = 'dymola-ci-tests/result'
result_whitelist_dir = 'dymola-ci-tests/result/ci_whitelist'
result_config_dir = 'dymola-ci-tests/result/configfiles'
result_plot_dir = 'dymola-ci-tests/result/charts'
result_syntax_dir = 'dymola-ci-tests/result/syntax'
result_regression_dir = 'dymola-ci-tests/result/regression'
result_interact_ci_dir = 'dymola-ci-tests/result/interact_CI'
result_ci_template_dir = 'dymola-ci-tests/result/ci_template'
result_check_result_dir = 'dymola-ci-tests/result/Dymola_check'
result_OM_check_result_dir = 'dymola-ci-tests/result/OM_check'


[Color]
CRED = '\033[91m'
CEND = '\033[0m'
green = '\033[0;32m'
yellow = '\033[33m'
blue = '\033[44m'
